function idx = findFirstMin(vec) 
% FINDFIRSTMIN finds the index j of the vector vec such that vec(j) <= vec(j-1) and vec(j) <= vec(j+1)
%    Note that this assumes: 
%        1) that vec is generated by some locally convex function 
%        2) vec is already listed in the desired sorting order
%
%    Also note: this function exists because e.g. lasso solver
%    eventually has many degrees of freedom when tau becomes
%    large; we would like to ignore this regime in certain
%    cases. This function thus finds the minimum before the
%    regime begins (where this 'makes sense' [what does it mean
%    to 'make sense' here?]). 

  % set result to first index trivially 
  j = 1;
  
  while j < length(vec) && vec(j+1) < vec(j)
    j = j+1;
  end

  idx = j;
end